service: serverless-twitter-proxy-app
provider:
  name: aws
  runtime: rust
  memorySize: 128
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
      Resource:
        - "arn:aws:dynamodb:ap-northeast-1:*:table/TwitterProxyVideoInfoCache"
        - "arn:aws:dynamodb:ap-northeast-1:*:table/TwitterProxyAccessCount"

package:
  individually: true

plugins:
  - serverless-rust

functions:
  resolve-url:
    handler: serverless-twitter-proxy-app.resolve-url
    events:
      - http:
          path: /api/lookup
          method: POST
    environment:
      CONSUMER_KEY: ${file(./.env.yml):CONSUMER_KEY}
      CONSUMER_SECRET: ${file(./.env.yml):CONSUMER_SECRET}
      ACCESS_TOKEN: ${file(./.env.yml):ACCESS_TOKEN}
      ACCESS_SECRET: ${file(./.env.yml):ACCESS_SECRET}

resources:
  Resources:
    TwitterProxyVideoInfoCache:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TwitterProxyVideoInfoCache
        AttributeDefinitions:
          - AttributeName: StatusId
            AttributeType: S
        KeySchema:
          - AttributeName: StatusId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TwitterProxyAccessCount:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TwitterProxyAccessCount
        AttributeDefinitions:
          - AttributeName: StatusId
            AttributeType: S
          - AttributeName: Date
            AttributeType: S
        KeySchema:
          - AttributeName: StatusId
            KeyType: HASH
          - AttributeName: Date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


custom:

  # this section customizes of the default
  # serverless-rust plugin settings
  rust:
    # custom docker tag
    dockerTag: '1.51'
    #  custom docker image
    dockerImage: 'softprops/lambda-rust'